load("render.star", "render")
load("http.star", "http")
load("encoding/base64.star", "base64")
load("schema.star", "schema")
load("math.star", "math")
load("cache.star", "cache")
load("encoding/json.star", "json")

Tesla_Icon = base64.decode("""
iVBORw0KGgoAAAANSUhEUgAAAA8AAAAPCAYAAAA71pVKAAAAAXNSR0IArs4c6QAAAXVJREFUOE+dk7tKA0EUhv+Z1RiLoCnsAks0hdEVjQoqRhG1thXs9A0svDyCFwTFQivfwcLKBCHWQhJzUVCD2AkBCw0psnvkDO66u4kEnOrM5fvnnPPPCPhGJDLTHeqp1fzrmjBjhULh2b0u3JP48Cj5If+8XMw5jBO0A8myYBFB0zTYAgpuB/KZ1NaLSmJxT4f8ERB/1ehP92qzgq4OwtJ+FEKqO2+FfSsRcToYn5xGvV73sJxyQv9C9i3kWXdg0zTxWL5Xm0PGmHOIRdPbFSwf9jf10oFBhGRyFifHR0hMTEFKCQZTDB5EIYTHGCX0C9u6RCgVc1hZiOF8/R2n12FcZsMtHWyGAXCN6Z0Ka6P6qWH1TG8NG4YxYJL2ZNd2kenFxvwH+taqaDQaCAaDbCUCgU7ks3cqtktwfOaG3ey+qhu4OZZl4aGUx2B8BBBCxTx47vhs58OWsYAU0vbRaxeREmx6YW6Bf71tl0AGwFwrEfen4P1vSSueYQes1/cAAAAASUVORK5CYII=
""")

BOLT_GREY = base64.decode("""
iVBORw0KGgoAAAANSUhEUgAAAAYAAAAHCAYAAAArkDztAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAYUlEQVQImWWNsQ1DIRDF/H4k9mCv64+RoL9xqFiAUV6qSFHi0pJl2ebDGMMAc049vxKQJLBNZjoz/V0rM917594LQERQVTyAAM05BVBVRMT/IyIE8Np7U1UGWGuptcY5hzdfLi2V01L0lQAAAABJRU5ErkJggg==
""")
BOLT = base64.decode("""
UklGRqIpAABXRUJQVlA4WAoAAAACAAAABQAABgAAQU5JTQYAAAD/////AABBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyAQICz4X/RgQ0BQ+D9aAgEyRJYe8x/EKfGBTMAyOpcCAongFdH/qEa4qxEAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gECAs+F/0YENAUPg/WgIBMkSWHvMfxCnxgUzAMjqXAgKJ4BXR/6hGuKsRAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIBAgLPhf9GBDQFD4P1oCATJElh7zH8Qp8YFMwDI6lwICieAV0f+oRrirEQBBTk1GUgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMOQAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0UtG3DxtIh6EG0iP4HPoLFZ1gECwBBTk1GUgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMOQAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0UtG3DxtIh6EG0iP4HPoLFZ1gECwBBTk1GUgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMOgAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0MBEgaxRaoHehKEf0PbggWn8UiWABBTk1GUgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMOgAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0MBEgaxRaoHehKEf0PbggWn8UiWABBTk1GVAAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMPAAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0UspEEB2cNnhO4Q7mI/gcrDovPYBEsAEFOTUZUAAAAAAAAAAAABQAABgAA9AEAAVZQOEw8AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQQHZw2eE7hDuYj+BysOi89gESwAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNFLKRBMdmDT6DM7mI/gcWh8VnWAQLQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNFLKRBMdmDT6DM7mI/gcWh8VnWAQLQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDkAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNFLRtw8bSIehBtIj+BxbFx2dYBAsAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDkAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNFLRtw8bSIehBtIj+BxbFx2dYBAsAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDARIGsUWqB3oShH9DyzCDZ/FIlgAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDARIGsUWqB3oShH9DyzCDZ/FIlgAQU5NRk4AAAAAAAAAAAAFAAAGAAD0AQABVlA4TDYAAAAvBYABAB8gkE3u79zSEJAk/v8cCQQI/rdEyJn/gC9WgVpIkuDobHQCL84iXHoR/Q/rWD6sIwFBTk1GTgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMNgAAAC8FgAEAHyCQTe7v3NIQkCT+/xwJBAj+t0TImf+AL1aBWkiS4OhsdAIvziJcehH9D+tYPqwjAUFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIJBN7u/c0hCQJP7/HAkECP63RMiZ/4AvVgGZgGV0LgUEEsEtov9RjXBXIwBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyCQTe7v3NIQkCT+/xwJBAj+t0TImf+AL1YBmYBldC4FBBLBLaL/UY1wVyMAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDkAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDLKNnNsM7u6NPqL/QaREvkekRAAAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDkAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDLKNnNsM7u6NPqL/QaREvkekRAAAQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gkE3u79zSEJAk/v8cCQQI/rdEyJn/gC9WAZmAZXQuBQQSwS2i/1GNcFcjAEFOTUZKAAAAAAAAAAAABQAABgAA9AEAAVZQOEwyAAAALwWAAQAfIJBN7u/c0hCQJP7/HAkECP63RMiZ/4AvVgGZgGV0LgUEEsEtov9RjXBXIwBBTk1GSgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMgAAAC8FgAEAHyCQTe7v3NIQkCT+/xwJBAj+t0TImf+AL1YBmYBldC4FBBJBDRH9j2qEuxoBQU5NRkoAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDIAAAAvBYABAB8gkE3u79zSEJAk/v8cCQQI/rdEyJn/gC9WAZmAZXQuBQQSQQ0R/Y9qhLsaAUFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gzO5iP4HFsHib1gEC0FOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gzO5iP4HFsHib1gEC0FOTUZIAAAAAAAAAAAABQAABgAA9AEAAVZQOEwvAAAALwWAAQAfIBBI8mfdYY35FwgQpLqWM/8BL9ZAQQAyDHsJBBJBwfWO6H+YgfBnBgIAQU5NRkgAAAAAAAAAAAAFAAAGAAD0AQABVlA4TC8AAAAvBYABAB8gEEjyZ91hjfkXCBCkupYz/wEv1kBBADIMewkEEkHB9Y7of5iB8GcGAgBBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqvWyARFBDR/6hGuKsRAABBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqvWyARFBDR/6hGuKsRAABBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqnXyARFBDR/6hGuKsRAABBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqnXyARFBDR/6hGuKsRAABBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqvWyARFBDR/6hGuKsRAABBTk1GRgAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMLQAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WgEzAMjqvWyARFBDR/6hGuKsRAABBTk1GSAAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMMAAAAC8FgAEAHyAQSPJn3WGN+RcIEKS6ljP/AS/WQCEbSXBy7iVYoEU4gYvofzgO8es8BEFOTUZIAAAAAAAAAAAABQAABgAA9AEAAVZQOEwwAAAALwWAAQAfIBBI8mfdYY35FwgQpLqWM/8BL9ZAIRtJcHLuJVigRTiBi+h/OA7x6zwEQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDARIGsUWqB3oShH9DyyCxWe5IVgAQU5NRlIAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDoAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNDARIGsUWqB3oShH9DyyCxWe5IVgAQU5NRlQAAAAAAAAAAAAFAAAGAAD0AQABVlA4TDwAAAAvBYABACcgICH8P2uB3BCQEPL/shBk22z+DLM5xHHmP4AvuBoNFLKRBAdnDZ4TuEO5iP4HFsHiM6w4LABBTk1GVAAAAAAAAAAAAAUAAAYAAPQBAAFWUDhMPAAAAC8FgAEAJyAgIfw/a4HcEJAQ8v+yEGTbbP4MsznEceY/gC+4Gg0UspEEB2cNnhO4Q7mI/gcWweIzrDgsAEFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gzO5iP4HFsHiMywOC0FOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gzO5iP4HFsHiMywOC0FOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw5AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRS0bcPG0iHoQbSI/gcWweIzLIoPAEFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw5AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRS0bcPG0iHoQbSI/gcWweIzLIoPAEFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDQwESBrFFqgd6EoR/Q8sgsVnsQg3AEFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDQwESBrFFqgd6EoR/Q8sgsVnsQg3AEFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gVO5iP4HFsHiMyzCCUFOTUZSAAAAAAAAAAAABQAABgAA9AEAAVZQOEw6AAAALwWAAQAnICAh/D9rgdwQkBDy/7IQZNts/gyzOcRx5j+AL7gaDRSykQTHZg0+gVO5iP4HFsHiMyzCCQ==
""")
def main(config):

    rep_cache = cache.get("teslafi")
    if rep_cache != None:
        print("Hit! Displaying cached data.")
        rep = json.decode(rep_cache)
    else:
        print("Miss! Calling TeslaFI API.")
        rep = http.get("https://www.teslafi.com/feed.php?token="+config.str("api"))
        if rep.status_code != 200:
            fail("TeslaFi request failed with status:", rep.status_code)
        rep=rep.json()
        cache.set("teslafi",json.encode(rep), ttl_seconds=60)
    
    name=rep['display_name']
    rangemi=rep['est_battery_range']
    if(config.bool("mi2km")==True):
        rangemi=math.round((float(rangemi)*1.60934)*100)/100
    # battlevel=rep['battery_level']
    chargelimit=rep['charge_limit_soc']
    batterylevel=rep['usable_battery_level']
    chargingstate=rep['charging_state']

    chargeColor=""
    if chargingstate!="Disconnected":
        image=BOLT
        chargeColor="#00FF00"
    else:
         image=BOLT_GREY
    if int(batterylevel)<=10:
        chargeColor="#FF0000"
    if int(batterylevel)<=20 and int(batterylevel) >10:
        chargeColor="#FFFF00"

    return render.Root(
        delay = 500,
        child = render.Box(
            padding = 1,
            child = render.Column(
                expanded = True,
                main_align = "space_around",
                cross_align = "center",
                children = [
                    render.Row(
                        expanded = True,
                        main_align = "space_around",
                        children = [
                        render.Text("%s" % name, font = "", color = ""),
                        
                        ],
                    ),
                    
                    
                    render.Row(
                        expanded = True,
                        main_align = "center",
                        children = [
                            render.Text("%s"%batterylevel,color = chargeColor),
                            render.Text("/",color = ""),
                            render.Text("%s%%" % chargelimit, font = "", color = "#e5a00d"),
                            render.Box(width = 8, height = 1),
                            render.Image(src=image),

                        ],
                    ),
                    render.Row(
                        expanded = True,
                        main_align = "center",
                        children = [
                            render.Text("Range: "),
                            render.Box(width = 1, height = 1),
                            render.Text("%s" % rangemi, font = "", color = "#e5a00d"),
                        ],
                    ),
                
                
                ],
            ),
        ),
    )

def get_schema():
    return schema.Schema(
        version = "1",
        fields = [
            schema.Text(
                id = "api",
                name = "API Key",
                desc = "API Key for TeslaFi",
                icon = "arrowUpFromBracket",
            ),
            schema.Toggle(
                id = "mi2km",
                name = "Mi/KM",
                desc = "Convert to KM",
                icon = "codeFork",
                default = True,
            ),
        ],
    )